services:

  automation-worker:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # image: django-worker:latest
    image: ghcr.io/laser-power-infra/django-worker:${APP_VERSION}
    # container_name:   automation-worker
    command: python manage.py consume_tender_tasks
    restart: unless-stopped
    env_file:
      - .env.production
    networks:
      - infra

  parsing-worker:
    image: ghcr.io/laser-power-infra/django-worker:${APP_VERSION}
    # container_name: parsing-worker
    command: python manage.py consume_tender_parsing
    restart: unless-stopped
    env_file:
      - .env.production
    networks:
      - infra

networks:
  infra:
    external: true